#+TITLE: Math 411 - Fall 2025
#+SUBTITLE: Introduction to Abstract Algebra 1
#+AUTHOR: Santiago Arango-Piñeros
#+EMAIL: sarangopiner@umass.edu
#+OPTIONS: toc:t num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../org-css.css"/>
#+HTML_HEAD:  <link rel="shortcut icon" type="image/x-icon" href="../../images/umass-favicon.ico">

* Coordinates
** Instructor
[[https://sarangop1728.github.io/][Santiago Arango-Piñeros]] (he/him/his).

My office is in *LGRT 1238*, and you can contact me via email at:
+ ~sarangopiner@umass.edu~.

** Teaching Assistant
Yuting Zhang
+ ~yutingzhang@umass.edu~

** Grader
Aaron Tian
+ ~atian@umass.edu~

** Lectures
|----------------+-------+---------------------+----------|
| /              | <     | <                   | <        |
| Section        | Days  | Time                | Place    |
|----------------+-------+---------------------+----------|
| 01-LEC (64725) | Tu, Th | 8:30 AM - 9:45 AM   | LGRT 177 |
| 02-LEC (64726) | Tu, Th | 10:00 AM - 11:15 AM | LGRT 206 |
|----------------+-------+---------------------+----------|

** Office hours
Feel free to drop by our office hours to ask questions or talk about the class.

|--------+-------------------+-----------|
| /      | <                 | <         |
| Days   | Time              | Place     |
|--------+-------------------+-----------|
| Tu     | 1:00 PM - 3:30 PM | LGRT 1522 |
| Wed, Fr | 1:30 PM - 3:30 PM | LGRT 1526 |
|--------+-------------------+-----------|

If the times above are not convenient, or if you would like to discuss a
private matter, send me an email.
  
* Course description
The focus of the course will be on studying /groups/. These are algebraic
structures that capture the notion of symmetry. Groups are ubiquitous in all
areas of mathematics (and the world around us). If you commit to this class,
you will master the essential concepts of group theory by the end of the
course.
** Prerequisites
*MATH 235* and either *CMPSCI 250* or *MATH 300*. In other words, we will need
some important concepts from linear algebra, and there will be an emphasis on
proofs and development of careful mathematical reasoning and writing.

** Textbook
+ */Algebra: Abstract and Concrete/* by Frederick M. Goodman. The book is
  freely available for download at the [[https://homepage.divms.uiowa.edu/~goodman/algebrabook.dir/algebrabook.html][author's website]].
+ As a complement of the textbook, we will use some of [[https://kconrad.math.uconn.edu/blurbs/][Keith Conrad's blurbs]] on
  group theory.

** Learning objectives

1. To learn the fundamental examples of groups: finitely generated abelian
   groups, dihedral groups, symmetric and alternating groups, and matrix
   groups.
2. To learn the axiomatic definition of a group and how to use it to prove
   basic properties.
3. To learn the concepts of subgroups, cosets, quotients, and how to combine
   these to derive Lagrange’s theorem.
4. To learn the concepts of homomorphisms and isomorphisms and Noether's
   isomorphism theorems.
5. To understand the structure theorem of finitely generated abelian groups in
   terms of the Smith normal form of a matrix with integer coefficients.
6. To learn what it means for a group to act on a set as well as the
   natural actions of each of the fundamental examples.

** Homework (~300 points~)
Homework assignments must be submitted through Gradescope by ~11:59 PM~ on the
due date. Each problem set contains 5 problems, and each problem is worth ~10
points~. This means that there is a ~50 points~ bonus on the homework. *Late
homework will not be graded.*

Collaboration with other students is highly encouraged! Nevertheless, every
student must write down their own solutions.

The use of professional academic typing software, such as [[https://typst.app/][Typst]] or
[[https://www.latex-project.org/][LaTeX]] (for example, via a free account at [[https://www.overleaf.com][Overleaf]]), is highly recommended
but not required. However, if the grader finds the writing difficult to read,
they reserve the right not to grade that particular answer.

+ ~PSET1~: Some examples of groups ([[https://www.dropbox.com/scl/fi/b5i8ayu0mxpzt1sbj5l27/pset1.pdf?rlkey=o3916firn5vuidmhinecvd0ho&dl=0][~pdf~]])([[https://www.dropbox.com/scl/fi/0uub9l5u6pso216iesn1o/pset1.tex?rlkey=cc1g4p7ltbzmbpzx6nofferut&dl=0][~tex~]])([[https://www.dropbox.com/scl/fi/tk00ud7mduyy1zio5baix/pset1-sol.pdf?rlkey=7a0c70e0lifhmiz1zot4e54ef&dl=0][~solution~]]) <2025-09-13 Sat 23:59>.
+ ~PSET2~: Basic properties of groups ([[https://www.dropbox.com/scl/fi/l7nq6825mdd7g55jijv24/pset2.pdf?rlkey=dl6i8wy7metiw6m0myawpsq9b&dl=0][~pdf~]])([[https://www.dropbox.com/scl/fi/9pbho8nj3yjmbprpnz5pj/pset2.tex?rlkey=ssvvl8vv68bml2qvbn2bv43ve&dl=0][~tex~]])([[https://www.dropbox.com/scl/fi/w8gnepiciawc0u15tot9o/pset2-sol.pdf?rlkey=oyc8uhdop12k3z8gnmcpm5ach&dl=0][~solution~]]) <2025-09-30 Tue 23:59>.
+ ~PSET3~: Cosets and Lagrange's theorem ([[https://www.dropbox.com/scl/fi/6pcxfv9io7z6kwu4apih3/pset3.pdf?rlkey=fmnd6uq9wkjuj71gml2th5uci&dl=0][~pdf~]])([[https://www.dropbox.com/scl/fi/osekgzpbd5bnvgmqi78rk/pset3.tex?rlkey=cutmmdo3iger3k7rpdo5gyv5o&dl=0][~tex~]])([[https://www.dropbox.com/scl/fi/ckmq30wut1053i5znaxkq/pset3-sol.pdf?rlkey=ptov92gbrgq5sdg5ol8519sg7&dl=0][~solution~]]) <2025-10-14 Tue 23:59>. 
+ ~PSET4~: The isomorphism theorems ([[https://www.dropbox.com/scl/fi/9atils9ndqw21s3l7587o/pset4.pdf?rlkey=cv7um1y5hsaglv7flr62bbk6h&dl=0][~pdf~]])([[https://www.dropbox.com/scl/fi/nxv95mjncgqwkenhqqn2p/pset4.tex?rlkey=a20rit6emx9y17rzyql4xqx4p&dl=0][~tex~]]) <2025-10-28 Tue 23:59>.
+ ~PSET5~: Finitely generated abelian groups (~pdf~)(~tex~) <2025-11-11 Tue 23:59>.
+ ~PSET6~: Symmetries of regular polyhedra (~pdf~)(~tex~)  <2025-11-25 Tue 23:59>.
+ ~PSET7~: Group actions (~pdf~)(~tex~) <2025-12-11 Thu 23:59>.

** Exams (~300 points~)
There will be three midterm exams. Each exam will have 5 questions. Each question will
be worth ~20 points~.
+ ~EXAM1~: Lectures 1-7. ([[https://www.dropbox.com/scl/fi/bmsjqie8nzscj5b07s4ai/exam1v1-solution.pdf?rlkey=v8d697jjlb8mlwwdts8n79lnb&dl=0][solution]]) <2025-09-25 Thu>
+ ~EXAM2~: Lectures 8-14. <2025-11-06 Thu>
+ ~EXAM3~: Lectures 18-22. <2025-12-09 Tue>
Question one will ask you to define a concept. Question two will ask you to
prove a result (of reasonable difficulty) from the assigned reading. Questions
3, 4, and 5 will be random problems related to the topics of the lectures.
** ``Mistakes were made'' essay (~100 points~)
This is a *handwritten* essay, due on the day of the final exam. It must
include at least:
+ three _mathematical_ mistakes you (the *student*) made during the course
  (either in a homework assignment, a previous test, or during self-study), and
+ two mathematical mistakes your favorite AI made when prompted with some group
  theory question;

along with thorough explanations of the nature of the errors and their
corrections. The essay will be graded on the mathematical accuracy of each
explanation: an accurate description of each mistake, together with a complete
correction, will be worth ~20 points~.

** Final exam (~300 points~)
The final exam will consist on six random problems related to the topics of the
lectures. Each problem will be worth ~50 points~. The emphasis will be on the
topics of lectures 1-14 and 18-22. 

** Grades
The perfect final grade is ~1000 points~. The alphabetical grade of the class
will be calculated as follows:
+ ~Homework grade = min(300, PSET1 + ... + PSET7)~.
+ ~Exams grade = EXAM1 + EXAM2 + EXAM3 + ESSAY + FINAL~
+ ~Final grade = Homework grade + Exams grade~.

| *Grade*  | A            | A$-$        | B$+$        | B           | B$-$        |
|----------+--------------+-------------+-------------+-------------+-------------|
| /        | <            |             |             |             |             |
| ~points~ | $[860,1000]$ | $[830,860)$ | $[780,830)$ | $[740,780)$ | $[690,740)$ |


| *Grade*  | C$+$        | C           | C$-$        | D$+$        | D           | F         |
|----------+-------------+-------------+-------------+-------------+-------------+-----------|
| /        | <           |             |             |             |             |           |
| ~points~ | $[650,690)$ | $[610,650)$ | $[560,610)$ | $[520,560)$ | $[480,520)$ | $[0,480)$ |

* Topics and schedule
It is the student's responsibility to read the material before the lecture.
During the lectures, we will focus on reviewing the key concepts, answering
questions, and working on examples.


|------------------+---------------------------------------+------------------|
| Date             | Lecture                               |          Reading |
|------------------+---------------------------------------+------------------|
| /                | <                                     |                < |
| <2025-09-02 Tue> | 1. [[https://www.dropbox.com/scl/fi/p1wxilymw0vyhqvnk3z0a/Lecture-1.pdf?rlkey=wz6pvevnvakryws6uz4t8jsgx&st=oihmxpsu&dl=0][What is symmetry?]]                  | 1.1 - 1.7, [[https://kconrad.math.uconn.edu/blurbs/grouptheory/whygroups.pdf][Blurb]] |
| <2025-09-04 Thu> | 2. [[https://www.dropbox.com/scl/fi/ye5ewjg4w53js9i9nnlqp/Lecture-2.pdf?rlkey=en0vp8k0mxcdldak8rpebqe5w&st=q1vmzgj1&dl=0][Examples of groups]]                 |        1.1 - 1.7 |
| <2025-09-09 Tue> | 3. [[https://www.dropbox.com/scl/fi/5fn0wkb6ejtsk79mqsjpc/Lecture-3.pdf?rlkey=2v43ltzmasna2gk3lyqmmoulk&dl=0][Abstract groups: first results]]     |        1.10, 2.1 |
| <2025-09-11 Thu> | 4. [[https://www.dropbox.com/scl/fi/17ji5counqyvroky0zxh7/Lecture-4.pdf?rlkey=ihh68st77av0gy3322151n05e&dl=0][Subgroups and cyclic groups]]        |              2.2 |
| <2025-09-16 Tue> | 5. [[https://www.dropbox.com/scl/fi/utckf9w72zu37yaec6f8c/Lecture-5.pdf?rlkey=fe58spmzyrto2y4xmrhr1lbh3&dl=0][Dihedral groups]]                    |              2.3 |
| <2025-09-18 Thu> | 6. [[https://www.dropbox.com/scl/fi/c4bwzgfb771pt55lv5r7k/Lecture-6.pdf?rlkey=66e9htb7zs3mo0avx0w6bcezy&dl=0][Homomorphisms and isomorphisms]]     |              2.4 |
| <2025-09-23 Tue> | 7. [[https://www.dropbox.com/scl/fi/4z4br5snua92kfmkyyqha/Lecture-7.pdf?rlkey=red8npkhxxxf51qcykp1rudpy&dl=0][The sign of a permutation]]          |            [[https://kconrad.math.uconn.edu/blurbs/grouptheory/sign.pdf][Blurb]] |
| <2025-09-25 Thu> | *Exam 1*                              |                  |
| <2025-09-30 Tue> | 8. [[https://www.dropbox.com/scl/fi/c49t3qqjya7v7pc29tazj/Lecture-8.pdf?rlkey=5qmji57c31u5npkxthnpqr0ya&dl=0][Cosets]]                             |              2.5 |
| <2025-10-02 Thu> | 9. [[https://www.dropbox.com/scl/fi/oxt143yka9abuh63wmpfd/Lecture-9.pdf?rlkey=iw757fm7u5t6e1jr5u2xlqy6h&dl=0][Lagrange's theorem]]                 |              2.5 |
| <2025-10-07 Tue> | 10. [[https://www.dropbox.com/scl/fi/5umx9xqjvzhxw28wvecpl/Lecture-10.pdf?rlkey=7o83fhinujrhqwrodnnmg0mco&dl=0][Noether's isomorphism theorems]]    |              2.7 |
| <2025-10-09 Thu> | 11. [[https://www.dropbox.com/scl/fi/yogahfmerlrevbc65y30r/Lecture-11.pdf?rlkey=w71u05arfw3kzyqiehc1ufx7d&dl=0][Direct products]]                   |              3.1 |
| <2025-10-14 Tue> | 12. [[https://www.dropbox.com/scl/fi/zekcw3zkkquwxs1zs8rlm/Lecture-12.pdf?rlkey=ooh7llneiqrcpf6reai4xdqc8&dl=0][Semidirect products]]               |              3.2 |
| <2025-10-16 Thu> | 13. Linear algebra over the integers  |              3.5 |
| <2025-10-21 Tue> | 14. Finitely generated abelian groups |              3.6 |
| <2025-10-23 Thu> | 15. Rotations of regular polyhedra    |              4.1 |
| <2025-10-28 Tue> | 16. The Dodecahedron and Icosahedron  |              4.2 |
| <2025-10-30 Thu> | 17. Reflections                       |              4.3 |
| <2025-11-04 Tue> | *No class* (election day)             |                  |
| <2025-11-06 Thu> | *Exam 2*                              |                  |
| <2025-11-11 Tue> | *No class* (veterans day)             |                  |
| <2025-11-13 Thu> | 18. Group actions                     |              5.1 |
| <2025-11-18 Tue> | 19. Counting orbits                   |              5.2 |
| <2025-11-20 Thu> | 20. Symmetries of groups              |              5.3 |
| <2025-11-25 Tue> | 21. Group actions and group structure |              5.4 |
| <2025-11-27 Thu> | *No class* (thanksgiving)             |                  |
| <2025-12-02 Tue> | 22. The Sylow theorems                |            [[https://kconrad.math.uconn.edu/blurbs/grouptheory/sylowpf.pdf][Blurb]] |
| <2025-12-04 Thu> | 23. Questions?                        |                  |
| <2025-12-09 Tue> | *Exam 3*                              |                  |
|------------------+---------------------------------------+------------------|

* Philosophy
** Adopt a growth mindset
  Your effort and attitude determine your abilities. Embrace challenges and
  failure as an oportunity to grow. Find inspiration in other people's success.
** Learning is the student's responsibility
Paraphrasing Galileo:
#+BEGIN_QUOTE
``You cannot teach a person *anything*; you can only help
them find it within themselves.''
#+END_QUOTE
We are all here to _understand_. My job as a more experienced learner is to
assist you on your journey. But you are responsible for investing the time and
effort necessary to learn.
** Doing hard things
This is hard work, and it will be frustrating at times. In my opinion, the
reward is well worth the investment, as it is often the case with challenging
endeavors. In the words of JFK:
#+BEGIN_QUOTE
``We choose to go to the Moon in this decade and do the other things, not
because they are easy, but because they are hard; because that goal will serve
to organize and measure the best of our energies and skills, because that
challenge is one that we are willing to accept, one we are unwilling to
postpone, and one we intend to win, and the others, too.''
#+END_QUOTE

** Everyone belongs in this classroom
We will subscribe to [[https://www.ams.org/publications/journals/notices/201610/rnoti-p1164.pdf][Federico's axioms]].

+ *Axiom 1.* Mathematical potential is equally present in different groups,
  irrespective of geographic, demographic, and economic boundaries.

+ *Axiom 2.* Everyone can have joyful, meaningful, and empowering mathematical
  experiences.

+ *Axiom 3.* Mathematics is a powerful, malleable tool that can be shaped and
  used differently by various communities to serve their needs.

+ *Axiom 4.* Every student deserves to be treated with dignity and respect.

* Administrative details
- Add/drop only through SPIRE.
- I do not keep a waiting list, and the mathematics department staff will not
  handle these matters.
- Final exams are kept by the mathematics department. Copies are available upon
  request.
** Drops, withdrawals, and incompletes
- Last day to add or drop with no record: <2025-09-08 Mon>.
- Last day to drop with W: <2025-10-28 Tue>.
- See the [[https://www.umass.edu/registrar/academic-calendar][academic calendar]] for other important dates.
- Incomplete grades are warranted only if a student is passing the course at the
  time of the request and if the course requirements can be completed by the
  end of the following semester. Read more [[https://www.umass.edu/natural-sciences/advising/petitions-and-forms/incomplete-grade-form][here]].

** Make-up exam policy
You must take the regular exam unless you qualify for an official make-up exam
approved by me, following the official make-up request procedure. Make sure you
read and understand the make-up exam procedure.

+ *Final exam conflict:* If you need a make-up exam due to a final exam
  schedule conflict, you must submit documentation from the Registrar's Office
  or other supporting documents at least two weeks before the scheduled exams.
  No exceptions will be made. No later than one week before the exam, you must
  submit a written request to me that includes: your name and UMass Amherst
  Student ID number, your section number, and the reason for requesting the
  make-up exam. You can request make-up exams through your SPIRE account: in
  SPIRE, go to Student Home > Final Exam Conflict.

+ *Religious observance:* If you must miss an exam due to religious observance,
  you must contact me within two weeks of the beginning of the semester.

+ *Medical reasons:* If you will be absent from an exam due to medical reasons,
  you must notify me at least one week in advance of the exam. If you have a
  medical emergency, you must notify me as soon as possible. In either case,
  you may need to provide documentation. You do not need to disclose personal
  details of your condition, but you must provide enough information to allow
  the absence to be excused.

+ *Other circumstances:* It is impossible to anticipate all possible
  situations. In the event of an exceptional circumstance not covered above,
  you must contact me and explain the problem. You must be prepared to provide
  a written statement if necessary. I will evaluate the reasons you provide and
  make a decision.

+ Note that there is *no re-taking of exams* in this course. If you are sick
  and take the exam anyway, you cannot re-take the exam later for a better
  grade. Regardless of the situation, if you do not feel you can take the exam
  on the scheduled date, you must inform me as soon as possible.
  
+ Make-up exams will *not* be given to accommodate travel plans.

+ I will ensure that taking a make-up exam does not represent any technical
  advantage. In particular, the questions will be completely different from
  those on the main exam.


** Class attendance policy
By UMass policy, students are expected to attend all regularly scheduled
classes at the University for which they are registered. When planning for the
tests and homework, I will assume that you have been following my lectures.
That being said, I will not enforce or grade for attendance. If you are not
able to attend to one of the lectures, make sure you read the notes for that
day and talk to other students to check if you missed anything important.

** Class etiquette
- I expect you to be present and refrain from using your phone.
- Arrive on time. If you arrive late, try to minimize your disruption.
- Laptops and tablets are allowed during the lectures, provided that you do not
  disrupt your fellow classmates and the lectures.

** Academic dishonesty 

Academic dishonesty includes but is not limited to: 
- *Cheating:* intentional use, and/or attempted use of trickery, artifice,
  deception, breach of confidence, fraud and/or misrepresentation of one's
  academic work.
- *Fabrication:* intentional and unauthorized falsification and/or invention of
  any information or citation in any academic exercise.
- *Plagiarism:* knowingly representing the words or ideas of another as one's
  own work in any academic exercise. This includes submitting without citation,
  in whole or in part, prewritten term papers of another or the research of
  another, including but not limited to commercial vendors who sell or
  distribute such materials.
- *Facilitating dishonesty:* knowingly helping or attempting to help another
  commit an act of academic dishonesty, including substituting for another in
  an examination, or allowing others to represent as their own one's papers,
  reports, or academic works.

Formal definitions of academic dishonesty, examples of various forms of
dishonesty, and the procedures which faculty must follow to penalize dishonesty
are detailed on the [[https://www.umass.edu/studentsuccess/academic-integrity][Academic Honesty website]]. Appeals must be filed within ten
days of notification by the Academic Honesty Office that a formal charge has
been filed by an instructor that suspects dishonesty. Contact the Academic
Honesty Office for more information on the process. The [[https://www.umass.edu/ombuds/][Ombuds Office]] is also
available to support individuals engaging with the Academic Honesty process.
The [[https://www.umass.edu/provost/][Provost’s Office]] is where appeals are processed and filed.

* Required statements
** Academic honesty statement
Since the integrity of the academic enterprise of any institution of higher
education requires honesty in scholarship and research, academic honesty is
required of all students at the University of Massachusetts Amherst. Academic
dishonesty is prohibited in all programs of the University. Academic dishonesty
includes but is not limited to: cheating, fabrication, plagiarism, and
facilitating dishonesty. Appropriate sanctions may be imposed on any student
who has committed an act of academic dishonesty. Instructors should take
reasonable steps to address academic misconduct. Any person who has reason to
believe that a student has committed academic dishonesty should bring such
information to the attention of the appropriate course instructor as soon as
possible. Instances of academic dishonesty not related to a specific course
should be brought to the attention of the appropriate department Head or Chair.
Since students are expected to be familiar with this policy and the commonly
accepted standards of academic integrity, ignorance of such standards is not
normally sufficient evidence of lack of intent
(http://www.umass.edu/dean_students/codeofconduct/acadhonesty/).

** Academic integrity statement
UMass Amherst is strongly committed to academic integrity, which is defined as
completing all academic work without cheating, lying, stealing, or receiving
unauthorized assistance from any other person, or using any source of
information not appropriately authorized or attributed. As a community, we hold
each other accountable and support each other’s knowledge and understanding of
academic integrity. Academic dishonesty is prohibited in all programs of the
University and includes but is not limited to: Cheating, fabrication,
plagiarism, lying, and facilitating dishonesty, via analogue and digital means.
Sanctions may be imposed on any student who has committed or participated in an
academic integrity infraction. Any person who has reason to believe that a
student has committed an academic integrity infraction should bring such
information to the attention of the appropriate course instructor as soon as
possible. All students at the University of Massachusetts Amherst have read and
acknowledged the Commitment to Academic Integrity and are knowingly responsible
for completing all work with integrity and in accordance with the policy:
(https://www.umass.edu/senate/book/academic-regulations-academic-integrity-policy).

** Accommodation statement
The University of Massachusetts Amherst is committed to providing an equal
educational opportunity for all students. If you have a documented physical,
psychological, or learning disability on file with Disability Services (DS),
you may be eligible for reasonable academic accommodations to help you succeed
in this course. If you have a documented disability that requires an
accommodation, please notify me within the first two weeks of the semester so
that we may make appropriate arrangements. For further information, please
visit Disability Services (https://www.umass.edu/disability/).

** Title IX statement
In accordance with Title IX of the Education Amendments of 1972 that prohibits
gender-based discrimination in educational settings that receive federal funds,
the University of Massachusetts Amherst is committed to providing a safe
learning environment for all students, free from all forms of discrimination,
including sexual assault, sexual harassment, domestic violence, dating
violence, stalking, and retaliation. This includes interactions in person or
online through digital platforms and social media. Title IX also protects
against discrimination on the basis of pregnancy, childbirth, false pregnancy,
miscarriage, abortion, or related conditions, including recovery. There are
resources here on campus to support you. A summary of the available Title IX
resources (confidential and non-confidential) can be found at the following
link: https://www.umass.edu/titleix/resources. You do not need to make a formal
report to access them. If you need immediate support, you are not alone. Free
and confidential support is available 24 hours a day / 7 days a week / 365 days
a year at the SASA Hotline 413-545-0800.
