#+TITLE: Math 411 - Fall 2025
#+AUTHOR: Santiago Arango-Piñeros
#+EMAIL: sarangopiner@umass.edu
#+OPTIONS: toc:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../style.css">


* Coordinates
** Instructor
[[https://sarangop1728.github.io/][Santiago Arango-Piñeros]] (he/him/his).
My office is LGRT 1238, and you can contact me via email at:
+ ~sarangopiner@umass.edu~.
** Office hours
+ Between 1:30 PM and 3:30 PM on Tuesdays.
+ Between 1:30 PM and 2:30 PM on and Thursdays.
+ If the times above are not convenient, send me an email.
  
* Course description
The focus of the course will be on studying /groups/. These are algebraic
structures that capture the notion of symmetry. Groups are ubiquitous in all
areas of mathematics (and the world around us). If you commit to this class,
you will master the essential concepts of group theory by the end of the
course.
** Prerequisites
*MATH 235* and either *CMPSCI 250* or *MATH 300*. In other words, we will need some
important concepts from linear algebra, and there will be an emphasis on proofs
and development of careful mathematical reasoning and writing.

** Textbook
+ */Algebra: Abstract and Concrete/* by Frederick M. Goodman. The book is
  freely available for download at the [[https://homepage.divms.uiowa.edu/~goodman/algebrabook.dir/algebrabook.html][author's web-site]].
+ As a complement of the textbook, we will use some of [[https://kconrad.math.uconn.edu/blurbs/][Keith Conrad's blurbs]] on
  group theory.

** Learning objectives

1. To learn the fundamental examples of groups: finitely generated abelian
   groups, dihedral groups, symmetric and alternating groups, and matrix
   groups.
2. To learn the axiomatic definition of a group and how to use it to prove
   basic properties.
3. To learn the concepts of subgroups, cosets, quotients, and how to combine
   these to derive Lagrange’s theorem.
4. To learn the concepts of homomorphisms and isomorphisms and Noether's
   isomorphism theorems.
5. To understand the structure theorem of finitely generated abelian groups in
   terms of the Smith normal form of a matrix with integer coefficients.
6. To learn what it means for a group to act on a set as well as the
   natural actions of each of the fundamental examples.

** Homework (~300 points~)
Homework assignments must be submitted through Gradescope by ~11:59 PM~ on the
due date. Each problem set contains 5 problems, and each problem is worth ~10
points~. This means that there is a ~50 points~ bonus on the homework. *Late
homework will not be graded.*

Collaboration with other students is highly encouraged! Nevertheless, every
student must write down their own solutions.

The use of professional academic typing software, such as [[https://typst.app/][Typst]] or
[[https://www.latex-project.org/][LaTeX]] (for example, via a free account at [[https://www.overleaf.com][Overleaf]]), is highly recommended
but not required. However, if the grader finds the writing difficult to read,
they reserve the right not to grade that particular answer.


+ ~PSET1~: Some examples of groups (~pdf~)(~tex~) <2025-09-11>.
+ ~PSET2~: Basic properties of groups (~pdf~)(~tex~) <2025-09-25>.
+ ~PSET3~: Lagrange's theorem (~pdf~)(~tex~) <2025-10-07>. 
+ ~PSET4~: The isomorphism theorems (~pdf~)(~tex~) <2025-10-16>.
+ ~PSET5~: Finitely generated abelian groups (~pdf~)(~tex~) <2025-11-06>.
+ ~PSET6~: Symmetries of regular polyhedra (~pdf~)(~tex~) <2025-11-18>.
+ ~PSET7~: Group actions (~pdf~)(~tex~) <2025-12-09>.

** Exams (~300 points~)
There will be three midterm exams. Each exam will have 5 questions. Each question will
be worth ~20 points~.
+ ~EXAM1~: Lectures 1-7. <2025-09-25 Thu>
+ ~EXAM2~: Lectures 8-14. <2025-11-06 Thu>
+ ~EXAM3~: Lectures 18-22. <2025-12-09 Tue>
Question one will ask you to define a concept. Question two will ask you to
prove a result (of reasonable difficulty) from the assigned reading. Questions
3, 4, and 5 will be random problems related to the topics of the lectures.
** ``Mistakes were made'' essay (~100 points~)
This is a *handwritten* essay, due on the day of the final exam. It must include
at least five mathematical mistakes the student made during the course, either
in a homework assignment, a previous test, or during self-study, along with a
thorough explanation of each error and its correction. The essay will be graded
on the mathematical accuracy of each correction: the complete correction of
each mistake will be worth ~20 points~.

** Final exam (~300 points~)
The final exam will consist on six random problems related to the topics of the
lectures. Each problem will be worth ~50 points~. The emphasis will be on the
topics of lectures 1-14 and 18-22.

** Grades
The perfect final grade is ~1000 points~. The alphabetical grade of the class
will be calculated as follows:
+ ~Homework grade = min(300, PSET1 + ... + PSET7)~.
+ ~Exams grade = EXAM1 + EXAM2 + EXAM3 + ESSAY + FINAL~
+ ~Final grade = Homework grade + Exams grade~.
| *Grade*  | A            | A$-$        | B$+$        | B           | B$-$        |
|----------+--------------+-------------+-------------+-------------+-------------|
| /        | <            |             |             |             |             |
| ~points~ | $[860,1000]$ | $[830,860)$ | $[780,830)$ | $[740,780)$ | $[690,740)$ |


| *Grade*  | C$+$        | C           | C$-$        | D$+$        | D           | F         |
|----------+-------------+-------------+-------------+-------------+-------------+-----------|
| /        | <           |             |             |             |             |           |
| ~points~ | $[650,690)$ | $[610,650)$ | $[560,610)$ | $[520,560)$ | $[480,520)$ | $[0,480)$ |

** Administrative Details
- Add/drop only through SPIRE.
- I do not keep a waiting list, and the mathematics department staff will not
  handle these matters.
- Final exams are kept by the mathematics department. Copies are available upon request.

*** Class Etiquette
- Class attendance is not mandatory. If you come to class, please refrain from
  texting or calls during lectures.
- Arrive on time; if you arrive late, try to minimize your disruption.
- Laptops/tablets are allowed during the lectures, provided that you do not
  disrupt your fellow classmates and the lectures.

*** Religious Observance
Notify in writing within the first two weeks if you will miss an exam for
religious reasons.

*** Drops, Withdrawals, and Incompletes
- Last day to drop with no record: Mon Sept 11
- Last day to drop with W: Tue Oct 31
- Incompletes only for compelling reasons, passing work, and likely completion

*** Make-up Exam Procedure
See: http://people.math.umass.edu/~siman/makeup.html

* Topics and schedule
It is the student's responsibility to read the material before the lecture.
During the lectures, we will focus on reviewing the key concepts, answering
questions, and working on examples.


|------------------+---------------------------------------+-----------|
| Date             | Lecture                               |   Reading |
|------------------+---------------------------------------+-----------|
| /                | <                                     |         < |
| <2025-09-02 Tue> | 1. What is symmetry?                  | 1.1 - 1.7 |
| <2025-09-04 Thu> | 2. Examples of groups                 | 1.1 - 1.7 |
| <2025-09-09 Tue> | 3. Abstract groups: first results     | 1.10, 2.1 |
| <2025-09-11 Thu> | 4. Subgroups and cyclic groups        |       2.2 |
| <2025-09-16 Tue> | 5. Dihedral groups                    |       2.3 |
| <2025-09-18 Thu> | 6. Homomorphisms and isomorphisms     |       2.4 |
| <2025-09-23 Tue> | 7. The sign of a permutation          |     [[https://kconrad.math.uconn.edu/blurbs/grouptheory/sign.pdf][Blurb]] |
| <2025-09-25 Thu> | *Exam 1*                              |           |
| <2025-09-30 Tue> | 8. Cosets                             |       2.5 |
| <2025-10-02 Thu> | 9. Lagrange's theorem                 |       2.5 |
| <2025-10-07 Tue> | 10. [[https://en.wikipedia.org/wiki/Emmy_Noether][Noether's]] isomorphism theorems    |       2.7 |
| <2025-10-09 Thu> | 11. Direct products                   |       3.1 |
| <2025-10-14 Tue> | 12. Semidirect products               |       3.2 |
| <2025-10-16 Thu> | 13. Linear algebra over the integers  |       3.5 |
| <2025-10-21 Tue> | 14. Finitely generated abelian groups |       3.6 |
| <2025-10-23 Thu> | 15. Rotations of regular polyhedra    |       4.1 |
| <2025-10-28 Tue> | 16. The Dodecahedron and Icosahedron  |       4.2 |
| <2025-10-30 Thu> | 17. Reflections                       |       4.3 |
| <2025-11-04 Tue> | *No class* (election day)             |           |
| <2025-11-06 Thu> | *Exam 2*                              |           |
| <2025-11-11 Tue> | *No class* (veterans day)             |           |
| <2025-11-13 Thu> | 18. Group actions                     |       5.1 |
| <2025-11-18 Tue> | 19. Counting orbits                   |       5.2 |
| <2025-11-20 Thu> | 20. Symmetries of groups              |       5.3 |
| <2025-11-25 Tue> | 21. Group actions and group structure |       5.4 |
| <2025-11-27 Thu> | *No class* (thanksgiving)             |           |
| <2025-12-02 Tue> | 22. The Sylow theorems                |     [[https://kconrad.math.uconn.edu/blurbs/grouptheory/sylowpf.pdf][Blurb]] |
| <2025-12-04 Thu> | 23. Questions?                        |           |
| <2025-12-09 Tue> | *Exam 3*                              |           |
|------------------+---------------------------------------+-----------|

* Philosophy
** Learning is the student's responsibility
Paraphrasing Galileo:
#+BEGIN_QUOTE
``You cannot teach a person *anything*; you can only help
them find it within themselves.''
#+END_QUOTE
We are all here to _understand_. My job as a more experienced learner is to
assist you on your journey. But you are responsible for investing the time and
effort necessary to learn.
** Doing hard things
This is hard work, and it will be frustrating at times. In my opinion, the
reward is well worth the investment, as it is often the case with challenging
endeavors. In the words of JFK:
#+BEGIN_QUOTE
``We choose to go to the Moon in this decade and do the other things, not
because they are easy, but because they are hard; because that goal will serve
to organize and measure the best of our energies and skills, because that
challenge is one that we are willing to accept, one we are unwilling to
postpone, and one we intend to win, and the others, too.''
#+END_QUOTE

** Everyone belongs in this classroom
We will subscribe to [[https://www.ams.org/publications/journals/notices/201610/rnoti-p1164.pdf][Federico's axioms]].

+ *Axiom 1.* Mathematical potential is equally present in different groups,
  irrespective of geographic, demographic, and economic boundaries.

+ *Axiom 2.* Everyone can have joyful, meaningful, and empowering mathematical
  experiences.

+ *Axiom 3.* Mathematics is a powerful, malleable tool that can be shaped and
  used differently by various communities to serve their needs.

+ *Axiom 4.* Every student deserves to be treated with dignity and respect.

* Accommodation Statement

The University of Massachusetts Amherst is committed to providing an equal
educational opportunity for all students. If you have a documented physical,
psychological, or learning disability on file with Disability Services (DS),
you may be eligible for reasonable academic accommodations to help you succeed
in this course. If you have a documented disability that requires an
accommodation, please notify me within the first two weeks of the semester so
that we may make appropriate arrangements.

* Academic Honesty Statement

The Academic Honesty Policy was established to ensure that the learning
environment at the university is honest and fair. The policy is designed to
provide faculty and students with options for handling incidents.

Academic dishonesty includes but is not limited to:

- *Cheating* — intentional use or attempted use of trickery or deception in one’s academic work
- *Fabrication* — intentional falsification and/or invention of any information or citation
- *Plagiarism* — knowingly representing the words or ideas of another as one’s own work
- *Facilitating dishonesty* — knowingly helping or attempting to help another commit an act of academic dishonesty

The Academic Honesty Board handles all cases of academic dishonesty on campus.
Formal definitions of academic dishonesty, examples of various forms of
dishonesty, and the procedures which faculty must follow to penalize dishonesty
are contained in the Academic Honesty Policy. There are two main pathways for
resolving cases where dishonesty is suspected: the informal resolution and the
formal charge. Both these paths require that the faculty member first inform
the student of the concern and offer a meeting. For more information:
http://www.umass.edu/honesty/.
