#+TITLE: Math 411 - Fall 2025
#+AUTHOR: Santiago Arango Piñeros
#+EMAIL: sarangopiner@umass.edu
#+OPTIONS: toc:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../style.css">

* Coordinates
** Instructor
[[https://sarangop1728.github.io/][Santiago Arango Piñeros]] (he/him/his).
My office is LGRT 1111, and you can contact me by email at:
+ ~sarangopiner@umass.edu~.
** Office hours
+ Between 1 PM to 3 PM on Tuesdays and Thursdays. (Location TBD)
+ If the above time is not convenient, send me an email.

* Philosophy
** Learning is the student's responsibility
Paraphrasing Galileo:
#+BEGIN_QUOTE
``You cannot teach a person *anything*; you can only help
them find it within themselves.''
#+END_QUOTE
We are all here to _understand_. My job as a
more experienced learner is to assist you on your journey. But you have to
invest time and effort to actually learn.
** Doing hard things
This is hard work, and it will be frustrating at times. In my opinion, the
reward is well worth the investment, as it is often the case with challenging
endeavors. In the words of JFK:
#+BEGIN_QUOTE
``We choose to go to the Moon in this decade and do the other things, not
because they are easy, but because they are hard; because that goal will serve
to organize and measure the best of our energies and skills, because that
challenge is one that we are willing to accept, one we are unwilling to
postpone, and one we intend to win, and the others, too.''
#+END_QUOTE

** Everyone belongs in this classroom
We will subscribe to [[https://www.ams.org/publications/journals/notices/201610/rnoti-p1164.pdf][Federico's axioms]].

+ *Axiom 1.* Mathematical potential is equally present in different groups,
  irrespective of geographic, demographic, and economic boundaries.

+ *Axiom 2.* Everyone can have joyful, meaningful, and empowering mathematical
  experiences.

+ *Axiom 3.* Mathematics is a powerful, malleable tool that can be shaped and
  used differently by various communities to serve their needs.

+ *Axiom 4.* Every student deserves to be treated with dignity and respect.

* Course description
The focus of the course will be on studying /groups/. These are algebraic
structures that capture the notion of symmetry. Groups are ubiquitous in all
areas of mathematics (and the world around us). If you commit to this class,
you will master the essential concepts of group theory by the end of the
course.
** Prerequisites
*MATH 235* and either *CMPSCI 250* or *MATH 300*. In other words, we will need some
important concepts from linear algebra, and there will be an emphasis on proofs
and development of careful mathematical reasoning and writing.

** Textbook
+ */Algebra: Abstract and Concrete/* by Frederick M. Goodman. The book is
  freely available for download at the [[https://homepage.divms.uiowa.edu/~goodman/algebrabook.dir/algebrabook.html][author's web-site]].
+ As a complement of the textbook, we will use some of [[https://kconrad.math.uconn.edu/blurbs/][Keith Conrad's blurbs]] on
  group theory.

** Learning objectives

1. To learn the fundamental examples of groups: finitely generated abelian
   groups, dihedral groups, symmetric and alternating groups, and matrix
   groups.
2. To learn the axiomatic definition of a group and how to use it to prove
   basic properties.
3. To learn the concepts of subgroups, cosets, quotients, and how to combine
   these to derive Lagrange’s theorem.
4. To learn the concepts of homomorphisms and isomorphisms and Noether's
   isomorphism theorems.
5. To understand the structure theorem of finitely generated abelian groups in
   terms of the Smith normal form of a matrix with integer coefficients.
6. To learn what it means for a group to act on a set as well as the
   natural actions of each of the fundamental examples.

** Homework (~35 points~)
Homework assignments must be submitted through Canvas by ~11:59 PM~ on the due
date. Each problem set contains 5 problems, and each problem is worth ~1 point~.
+ ~PSET1~: Some examples of groups (~pdf~)(~tex~) <2025-09-11>.
+ ~PSET2~: Basic properties of groups (~pdf~)(~tex~) <2025-09-25>.
+ ~PSET3~: Lagrange's theorem (~pdf~)(~tex~) <2025-10-07>. 
+ ~PSET4~: The isomorphism theorems (~pdf~)(~tex~) <2025-10-16>.
+ ~PSET5~: Finitely generated abelian groups (~pdf~)(~tex~) <2025-11-06>.
+ ~PSET6~: Symmetries of regular polyhedra (~pdf~)(~tex~) <2025-11-18>.
+ ~PSET7~: Group actions (~pdf~)(~tex~) <2025-12-09>.

** Exams (~72 points~)
There will be three exams. Each exam will have 6 questions. Each question will
be worth ~4 points~.
+ ~EXAM1~: Lectures 1-7. <2025-09-25 Thu>
+ ~EXAM2~: Lectures 8-14. <2025-11-06 Thu>
+ ~EXAM3~: Lectures 18-22. <2025-12-09 Tue>
Question one will ask you to define a concept. Question two will ask you to
prove a result (of reasonable difficulty) from the assigned reading. Questions
3, 4, and 5 will be random problems related to the topics of the lectures.
** Final exam
The final exam is not a final exam. Instead, it is an opportunity for you to
learn from your mistakes. For each one of the homework problems or exam
questions that you previously got wrong, you will have the chance to:
1. Explain what was your mistake.
2. Write down a correct solution to the problem/question.
If you successfully do this, you will earn the points for that problem/question.
Note that you may not present a problem that you did not turn in before. Keep
in mind that taking the final exam is optional, and students with a perfect
score (~107 points~) have no reason to take it.

Some remarks:
+ It is likely that you won't have time to solve more than 8 questions during
  the final exam.
+ Since one exam question is worth four times one homework problem, it makes
  sense to prioritize the former.
** Grades
The grade of the class will be calculated by adding the total number of points
obtained after the final exam.
| *Grade*  | A          | A$-$      | B$+$      | B         | B$-$      |
|----------+------------+-----------+-----------+-----------+-----------|
| ~points~ | $\geq 100$ | $\geq 95$ | $\geq 90$ | $\geq 85$ | $\geq 80$ |


| *Grade*  | C$+$      | C        | C$-$     | D$+$      | D         | F      |
|----------+-----------+----------+----------+-----------+-----------+--------|
| ~points~ | $\geq 75$ | $\geq70$ | $\geq65$ | $\geq 60$ | $\geq 55$ | $< 55$ |

* Topics and schedule
It is the student's responsibility to read the material before the lecture.
During the lectures, we will focus on reviewing the key concepts, answering
questions, and working on examples.


|------------------+---------------------------------------+-----------|
| Date             | Lecture                               |   Reading |
|------------------+---------------------------------------+-----------|
| <2025-09-02 Tue> | 1. What is symmetry?                  | 1.1 - 1.7 |
| <2025-09-04 Thu> | 2. Examples of groups                 | 1.1 - 1.7 |
| <2025-09-09 Tue> | 3. Abstract groups: first results     | 1.10, 2.1 |
| <2025-09-11 Thu> | 4. Subgroups and cyclic groups        |       2.2 |
| <2025-09-16 Tue> | 5. Dihedral groups                    |       2.3 |
| <2025-09-18 Thu> | 6. Homomorphisms and isomorphisms     |       2.4 |
| <2025-09-23 Tue> | 7. The sign of a permutation          |     [[https://kconrad.math.uconn.edu/blurbs/grouptheory/sign.pdf][Blurb]] |
| <2025-09-25 Thu> | *Exam 1*                              |           |
| <2025-09-30 Tue> | 8. Cosets                             |       2.5 |
| <2025-10-02 Thu> | 9. Lagrange's theorem                 |       2.5 |
| <2025-10-07 Tue> | 10. [[https://en.wikipedia.org/wiki/Emmy_Noether][Noether's]] isomorphism theorems    |       2.7 |
| <2025-10-09 Thu> | 11. Direct products                   |       3.1 |
| <2025-10-14 Tue> | 12. Semidirect products               |       3.2 |
| <2025-10-16 Thu> | 13. Linear algebra over the integers  |       3.5 |
| <2025-10-21 Tue> | 14. Finitely generated abelian groups |       3.6 |
| <2025-10-23 Thu> | 15. Rotations of regular polyhedra    |       4.1 |
| <2025-10-28 Tue> | 16. The Dodecahedron and Icosahedron  |       4.2 |
| <2025-10-30 Thu> | 17. Reflections                       |       4.3 |
| <2025-11-04 Tue> | *No class* (election day)             |           |
| <2025-11-06 Thu> | *Exam 2*                              |           |
| <2025-11-11 Tue> | *No class* (veterans day)             |           |
| <2025-11-13 Thu> | 18. Group actions                     |       5.1 |
| <2025-11-18 Tue> | 19. Counting orbits                   |       5.2 |
| <2025-11-20 Thu> | 20. Symmetries of groups              |       5.3 |
| <2025-11-25 Tue> | 21. Group actions and group structure |       5.4 |
| <2025-11-27 Thu> | *No class* (thanksgiving)             |           |
| <2025-12-02 Tue> | 22. The Sylow theorems                |     [[https://kconrad.math.uconn.edu/blurbs/grouptheory/sylowpf.pdf][Blurb]] |
| <2025-12-04 Thu> | 23. Questions?                        |           |
| <2025-12-09 Tue> | *Exam 3*                              |           |
|------------------+---------------------------------------+-----------|


* Accommodation Statement

The University of Massachusetts Amherst is committed to providing an equal
educational opportunity for all students. If you have a documented physical,
psychological, or learning disability on file with Disability Services (DS),
you may be eligible for reasonable academic accommodations to help you succeed
in this course. If you have a documented disability that requires an
accommodation, please notify me within the first two weeks of the semester so
that we may make appropriate arrangements.

* Academic Honesty Statement

The Academic Honesty Policy was established to ensure that the learning
environment at the university is honest and fair. The policy is designed to
provide faculty and students with options for handling incidents.

Academic dishonesty includes but is not limited to:

- *Cheating* — intentional use or attempted use of trickery or deception in one’s academic work
- *Fabrication* — intentional falsification and/or invention of any information or citation
- *Plagiarism* — knowingly representing the words or ideas of another as one’s own work
- *Facilitating dishonesty* — knowingly helping or attempting to help another commit an act of academic dishonesty

The Academic Honesty Board handles all cases of academic dishonesty on campus.
Formal definitions of academic dishonesty, examples of various forms of
dishonesty, and the procedures which faculty must follow to penalize dishonesty
are contained in the Academic Honesty Policy. There are two main pathways for
resolving cases where dishonesty is suspected: the informal resolution and the
formal charge. Both these paths require that the faculty member first inform
the student of the concern and offer a meeting. For more information:
http://www.umass.edu/honesty/.
