#+TITLE: Arithmetic of elliptic curves
#+SUBTITLE: Math 714 - Fall 2026
#+AUTHOR: Santiago Arango-Piñeros
#+EMAIL: sarangopiner@umass.edu
#+OPTIONS: toc:1 num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../../org-css.css"/>
#+HTML_HEAD:  <link rel="shortcut icon" type="image/x-icon" href="../../images/umass-favicon.ico">


* Coordinates
** Instructor
[[https://sarangop1728.github.io/][Santiago Arango-Piñeros]], Ph.D. (He/Him).

My office is in *LGRT 1238*, and you can contact me via email at:
+ ~sarangopiner@umass.edu~.
  
** Lectures
|----------------+---------+---------------------+----------|
|      <c>       |   <c>   |         <c>         |   <c>    |
|    Section     |  Days   |        Time         |  Place   |
|----------------+---------+---------------------+----------|
| 01-LEC (20397) | Tu, Thu | 10:00 AM - 11:15 AM | LGRT 206 |
|----------------+---------+---------------------+----------|

** Office hours

TBD.

* Course description

This will be a graduate course introducing the arithmetic of elliptic
curves. My goal as an instructor is that, after taking this course, a dedicated
student will:

1. Be comfortable with the contents of Silverman's book: /[[https://www.math.brown.edu/johsilve/AECHome.html][The Arithmetic Of
   Elliptic Curves]]/. (In particular, with Chapters 3, 5, 7, 8, 9, and 10.)
2. Be ready to tackle a research problem in this subject.
3. Know how to use the computer algebra system ~Magma~ to design experiments
   that inform your research in this area.

To accomplish these goals, the students will:
1. Read the book in their own time, and solve as many problems as they possibly
   can.
2. Read a research paper and write a report about it.
3. Use ~Magma~ to:
   + Solve the computational problems in the book.
   + Confirm relevant computations from their chosen research paper, and
     include them in their reports.

I will not repeat the contents of the assigned reading during the lectures.
Instead, I will assume that everyone has read the material and has questions
about the subjects. The time of the lecture will be spent emphasizing the
subtle points, asking questions about the reading, and working through related
examples in ~Magma~.
We will use the remaining time to solve homework problems.

** Textbook

+ ~[S]~ J. H. Silverman, /The Arithmetic of Elliptic Curves/, 2nd edition,
  Graduate Texts in Mathematics 106, Springer, 2009. ([[https://www.math.brown.edu/johsilve/AEC/AECErrata.pdf][errata]])

** Other references

- Milne, [[https://www.jmilne.org/math/Books/EC2.pdf][/Elliptic Curves/]].
- Diamond & Shurman, [[https://link.springer.com/book/10.1007/978-0-387-27226-9][/A first course in modular forms/]].
- Poonen, [[https://math.mit.edu/~poonen/papers/curves.pdf][/Lectures on rational points on curves/]].
- Poonen, [[https://bookstore.ams.org/gsm-186][/Rational points on varieties/]]. ([[https://math.mit.edu/~poonen/papers/Qpoints-errata.pdf][errata]])
- Poonen, [[https://math.mit.edu/~poonen/papers/elliptic.pdf][/Elliptic curves/]]. 
- Siksek, [[https://samirsiksek.github.io/siksek.github.io/modcurves2.pdf][/Explicit arithmetic of modular curves/]].
- Silverman, [[https://link.springer.com/book/10.1007/978-1-4612-0851-8][/Advanced topics in the arithmetic of elliptic curves/]]. ([[https://www.math.brown.edu/johsilve/ATAEC/ATAECErrata.pdf][errata]])
- Sutherland, [[https://math.mit.edu/classes/18.783/2017/lectures.html][MIT Math 18.783 - Elliptic Curves]].
- ~LMFDB~, Elliptic curve database ([[https://www.lmfdb.org/EllipticCurve/Q/][Over \(\mathbb{Q}\)]], [[https://www.lmfdb.org/EllipticCurve/][over number fields]]).
- ~Magma~, the [[https://magma.maths.usyd.edu.au/magma/handbook/][handbook]] and [[https://magma.maths.usyd.edu.au/calc/][calculator]].

** Grades
Your grade will be computed as a weighted average of the following work:
+ [[*Reading, participation, collaboration, and engagement][Reading, participation, collaboration, and engagement]] (~20%~)
+ [[*Homework][Homework]] (~42%~)
+ [[*Final Project][Final Project]] (~38%~)
  
I will have a /one-hour/ meeting with each student *before the end of classes*.
For this meeting, the student will bring their *solved problems* and *research
report*. We will talk about your homework solutions, and discuss
possible future research directions based on your report.
+ You are responsible for scheduling this meeting with me (in person) before
  <2026-12-16 Wed>.

I will compute your grade as the weighted average \[
0.20\cdot(\text{participation}) + 0.42\cdot(\text{homework}) +
0.38\cdot(\text{final project}), \] of the number of points \( \in [0,100]\) in
each category, and then use the following tables to convert it into a letter
grade.

| *Grade* |     A      |   A$-$    |   B$+$    |     B     |   B$-$    |
|---------+------------+-----------+-----------+-----------+-----------|
|   <c>   |    <c>     |    <c>    |    <c>    |    <c>    |    <c>    |
| score   | $[93,100]$ | $[90,93)$ | $[87,90)$ | $[83,87)$ | $[80,83)$ |

| *Grade* |   C$+$    |     C     |   C$-$    |   D$+$    |     D     |    F     |
|---------+-----------+-----------+-----------+-----------+-----------+----------|
|   <c>   |    <c>    |    <c>    |    <c>    |    <c>    |    <c>    |   <c>    |
|  score  | $[77,80)$ | $[73,77)$ | $[70,73)$ | $[67,70)$ | $[60,67)$ | $[0,60)$ |
   
* Schedule and reading

Here is a weekly schedule of the topics we will cover. It is the student's
responsibility to read *ahead* of the lecture, and to come prepared with
questions.

If you are lost in the weeds, read [[https://math.mit.edu/~poonen/papers/elliptic.pdf][this article]] to remind yourself of the big
picture.

I will assume familiarity with Chapters I and II in ~[S]~. To complement some
of the algebraic geometry background, I recommend Chapters I and II in
[[https://math.mit.edu/~poonen/papers/curves.pdf][curves.pdf]].

|-----+------------------+-----------------------------------------------------------+------------------------------|
|     |       Date       | Topic                                                     | Reading                      |
| <c> |       <c>        |                                                           |                              |
|-----+------------------+-----------------------------------------------------------+------------------------------|
|  1  | <2026-09-08 Tue> | Elliptic curves as Riemann surfaces                       | ([[https://link.springer.com/book/10.1007/978-0-387-27226-9][Diamond & Shurman]]) 1.3, 1.4 |
|  2  | <2026-09-10 Thu> | General theory                                            | III.1, III.2, III.3, III.4   |
|  3  | <2026-09-15 Tue> |                                                           | III.5, III.6, III.7          |
|  4  | <2026-09-17 Thu> |                                                           | III.8, III.9, III.10         |
|  5  | <2026-09-22 Tue> | Elliptic curves over finite fields                        | V.1, V.2                     |
|  6  | <2026-09-24 Thu> |                                                           | V.3, V.4                     |
|  7  | <2026-09-29 Tue> | Elliptic curves over local fields                         | VII.1, VII.2, VII.3          |
|  8  | <2026-10-01 Thu> |                                                           | VII.4, VII.5                 |
|  9  | <2026-10-06 Tue> |                                                           | VII.6, VII.7                 |
| 10  | <2026-10-08 Thu> | Galois cohomology                                         | B.1, B.2, B.3 (appendix)     |
| 11  | <2026-10-13 Tue> | The Mordell--Weil theorem                                 | VIII.1, VIII.2               |
| 12  | <2026-10-15 Thu> |                                                           | VIII.3, VIII.4               |
| 13  | <2026-10-20 Tue> |                                                           | VIII.5, VIII.6               |
| 14  | <2026-10-22 Thu> |                                                           | VIII.7, VIII.8               |
| 15  | <2026-10-27 Tue> |                                                           | VIII.9, VIII.10              |
| 16  | <2026-10-29 Thu> |                                                           | VIII.11                      |
|     | <2026-11-03 Tue> | @@html:<span style="color:red">@@No class@@html:</span>@@ | (Election Day)               |
| 17  | <2026-11-05 Thu> | Integral points                                           | IX.1, IX.2, IX.3             |
| 18  | <2026-11-10 Tue> |                                                           | IX.4, IX.6, IX.7             |
| 19  | <2026-11-12 Thu> | Twisting, Selmer, and Ш                                   | X.1, X.2                     |
| 20  | <2026-11-17 Tue> |                                                           | X.3, X.4                     |
| 21  | <2026-11-19 Thu> |                                                           | X.5, X.6                     |
|     | <2026-11-24 Tue> | @@html:<span style="color:red">@@No class@@html:</span>@@ | (Wednesday schedule)         |
|     | <2026-11-26 Thu> | @@html:<span style="color:red">@@No class@@html:</span>@@ | (Thanksgiving)               |
| 22  | <2026-12-01 Tue> | Complex multiplication                                    | C.11                         |
| 23  | <2026-12-03 Thu> | The Tate curve                                            | C.14                         |
| 24  | <2026-12-08 Tue> | The \(L\)-function and BSD                                | C.16                         |
| 25  | <2026-12-10 Thu> | The Sato--Tate conjecture                                 | C.21                         |
| 26  | <2026-12-15 Tue> | Intro to modular curves                                   | ([[https://samirsiksek.github.io/siksek.github.io/modcurves2.pdf][Siksek]]) Chapters 2, 3, 4.   |
|-----+------------------+-----------------------------------------------------------+------------------------------|

* Reading, participation, collaboration, and engagement

Passing or failing this component will ultimately be left to my judgement. I
will decide that you passed if:
+ You attended at least 80% of the lectures.
+ You kept on schedule with the assigned reading.
+ You participated actively and consistently in the class discussions.
+ You interacted/collaborated with your colleagues in a respectful and
  productive way.
+ I am convinced that your homework solutions reflect your own understanding.
+ I am convinced that your final project reflects your own understanding, and
  was written by yourself.

Failing this component means that you will also @@html:<span
style="color:red">@@fail the course@@html:</span>@@, regardless of your
homework and final project.

* Homework

Every student enrolled in this class must solve (and type the solutions of)

\[42 = (-80538738812075974)^3 + (80435758145817515)^3 + (12602123297335631)^3 \]

problems of their choosing. I recommend choosing your favorite three
problems each week, from the chapter in ~[S]~ that you are currently reading.

+ At least 10 of these problems should be solved using ~Magma~ in some crucial
  way.
+ Collaboration is encouraged, but you [[https://www.twincities.com/2026/08/11/bret-stephens-im-begging-you-never-ever-write-with-ai/][must]] write your own solutions.
+ Resist the temptation of asking AI for a full solution. Try asking your
  fellow students or me before doing this, or use the machine to coach you
  towards a solution.
+ Your solutions are due on <2026-12-04 Fri 23:59> by email.
  
* Final Project

You will choose a research article on the arithmetic of elliptic curves to
study throughout the semester. 

I curated a list of [[* Suggested papers][suggested papers]], but if you have an article not on the
list that you want to read, talk to me about it!

Based on your reading of this article, you will write a *research report* that:
1. Gives a brief explanation of the relevant objects under study. 
2. Explains the results of the paper.
3. Produces computational evidence that supports the results of the article.

The research report is due on <2026-12-04 Fri 23:59> by email.


** Suggested papers
+ Cremona & Sutherland, [[https://arxiv.org/pdf/0901.0120][On a theorem of Mestre and Schoof]].
+ Dokchitser & Dokchitser, [[https://arxiv.org/pdf/1104.5031][Surjectivity of mod \(2^n\) representations of elliptic curves]].
+ Lenstra, [[https://pages.cs.wisc.edu/~cs812-1/Lenstra1987.pdf][Factoring integers with elliptic curves]].
+ Klagsbrun & Lemke Oliver, [[https://lemkeoliver.github.io/papers/12-TamagawaTwoTorsion.pdf][The distribution of the Tamagawa ratio in the
  family of elliptic curves with a two-torsion point]].
+ Sutherland, [[https://arxiv.org/pdf/1107.1140][Identifying supersingular elliptic curves]].
+ Schoof, [[https://reneschoof.github.io/ctpts.pdf][Elliptic curves over finite fields and the computation of square roots mod /p/]].
+ Schoof & Tzanakis, [[https://reneschoof.github.io/AA-schoof-tzanakis.pdf][Integral points on a modular curve of level 11]].
+ Wong, [[https://arxiv.org/pdf/math/0606405][Quadratic twists of pairs of elliptic curves]].
+ Wong, [[https://www.cambridge.org/core/journals/compositio-mathematica/article/on-the-density-of-elliptic-curves/DAFCBAD799FCADA01008C034CE85A176][On the density of elliptic curves]].
+ Zywina, [[https://davidzywina.github.io/papers/NoJumps.pdf][An elliptic surface with infinitely many fibers for which the rank does not jump]].
+ Zywina, [[https://davidzywina.github.io/papers/Rank2.pdf][There are infinitely many elliptic curves over the rationals of rank 2]].

* Philosophy
** Adopt a growth mindset
  Your effort and attitude determine your abilities. Embrace challenges and
  failure as an opportunity to grow. Find inspiration in other people's success.

** Learning is the student's responsibility
Paraphrasing Galileo:
#+BEGIN_QUOTE
``You cannot teach a person *anything*; you can only help
them find it within themselves.''
#+END_QUOTE
We are all here to _understand_. My job as a more experienced learner is to
assist you on your journey. But you are responsible for investing the time and
effort necessary to learn.

** Doing hard things
This is hard work, and it will be frustrating at times. In my opinion, the
reward is well worth the investment, as is often the case with challenging
endeavors. In the words of JFK:
#+BEGIN_QUOTE
``We choose to go to the Moon in this decade and do the other things, not
because they are easy, but because they are hard; because that goal will serve
to organize and measure the best of our energies and skills, because that
challenge is one that we are willing to accept, one we are unwilling to
postpone, and one we intend to win, and the others, too.''
#+END_QUOTE

** Everyone belongs in this classroom
We will subscribe to [[https://www.ams.org/publications/journals/notices/201610/rnoti-p1164.pdf][Federico's axioms]].

+ *Axiom 1.* Mathematical potential is equally present in different groups,
  irrespective of geographic, demographic, and economic boundaries.

+ *Axiom 2.* Everyone can have joyful, meaningful, and empowering mathematical
  experiences.

+ *Axiom 3.* Mathematics is a powerful, malleable tool that can be shaped and
  used differently by various communities to serve their needs.

+ *Axiom 4.* Every student deserves to be treated with dignity and respect.

* Administrative details

- Add/drop only through SPIRE.
- I do not keep a waiting list, and the mathematics department staff will not
  handle these matters.

** Drops, withdrawals, and incompletes
The dates below are the *graduate student* deadlines for Fall 2026.
- Last day to add or drop with no record: <2026-09-21 Mon>.
- Last day to drop with DR: <2026-11-04 Wed>.
- See the [[https://www.umass.edu/registrar/academic-calendar][academic calendar]] for other important dates.
- Incomplete grades are warranted only if a student is passing the course at the
  time of the request and if the course requirements can be completed by the
  end of the following semester. Read more [[https://www.umass.edu/natural-sciences/advising/petitions-and-forms/incomplete-grade-form][here]].

** Class attendance policy
By UMass policy, students are expected to attend all regularly scheduled
classes at the University for which they are registered. This is a small,
discussion-based graduate course: the lectures /are/ the course, and they do
not work if you are not in the room. For this reason I do keep track of
attendance, and attending at least ~80%~ of the lectures is one of the
conditions for passing the [[*Reading, participation, collaboration, and engagement][participation component]].

If you cannot attend a lecture, let me know in advance when possible, read the
corresponding sections yourself, and talk to your classmates to check whether
you missed anything important. If something in your life is making regular
attendance difficult, come talk to me early rather than late.

** Class etiquette
- I expect you to be present and refrain from using your phone.
- Arrive on time. If you arrive late, try to minimize your disruption.
- Laptops and tablets are allowed during lectures, provided that you do not
  disrupt your fellow classmates or the lecture.

** Academic dishonesty 

Academic dishonesty includes but is not limited to: 
- *Cheating:* intentional use, and/or attempted use of trickery, artifice,
  deception, breach of confidence, fraud, and/or misrepresentation of one's
  academic work.
- *Fabrication:* intentional and unauthorized falsification and/or invention of
  any information or citation in any academic exercise.
- *Plagiarism:* knowingly representing the words or ideas of another as one's
  own work in any academic exercise. This includes submitting without citation,
  in whole or in part, prewritten term papers of another or the research of
  another, including but not limited to commercial vendors who sell or
  distribute such materials.
- *Facilitating dishonesty:* knowingly helping or attempting to help another
  commit an act of academic dishonesty, including substituting for another in
  an examination, or allowing others to represent as their own one's papers,
  reports, or academic works.

Formal definitions of academic dishonesty, examples of various forms of
dishonesty, and the procedures which faculty must follow to penalize dishonesty
are detailed on the [[https://www.umass.edu/studentsuccess/academic-integrity][Academic Honesty website]]. Appeals must be filed within ten
days of notification by the Academic Honesty Office that a formal charge has
been filed by an instructor who suspects dishonesty. Contact the Academic
Honesty Office for more information on the process. The [[https://www.umass.edu/ombuds/][Ombuds Office]] is also
available to support individuals engaging with the Academic Honesty process.
The [[https://www.umass.edu/provost/][Provost’s Office]] is where appeals are processed and filed.

* Required statements
** Academic honesty statement
Since the integrity of the academic enterprise of any institution of higher
education requires honesty in scholarship and research, academic honesty is
required of all students at the University of Massachusetts Amherst. Academic
dishonesty is prohibited in all programs of the University. Academic dishonesty
includes but is not limited to: cheating, fabrication, plagiarism, and
facilitating dishonesty. Appropriate sanctions may be imposed on any student
who has committed an act of academic dishonesty. Instructors should take
reasonable steps to address academic misconduct. Any person who has reason to
believe that a student has committed academic dishonesty should bring such
information to the attention of the appropriate course instructor as soon as
possible. Instances of academic dishonesty not related to a specific course
should be brought to the attention of the appropriate department head or chair.
Since students are expected to be familiar with this policy and the commonly
accepted standards of academic integrity, ignorance of such standards is not
normally sufficient evidence of lack of intent
(http://www.umass.edu/dean_students/codeofconduct/acadhonesty/).

** Academic integrity statement
UMass Amherst is strongly committed to academic integrity, which is defined as
completing all academic work without cheating, lying, stealing, or receiving
unauthorized assistance from any other person, or using any source of
information not appropriately authorized or attributed. As a community, we hold
each other accountable and support each other’s knowledge and understanding of
academic integrity. Academic dishonesty is prohibited in all programs of the
University and includes but is not limited to: cheating, fabrication,
plagiarism, lying, and facilitating dishonesty, via analogue and digital means.
Sanctions may be imposed on any student who has committed or participated in an
academic integrity infraction. Any person who has reason to believe that a
student has committed an academic integrity infraction should bring such
information to the attention of the appropriate course instructor as soon as
possible. All students at the University of Massachusetts Amherst have read and
acknowledged the Commitment to Academic Integrity and are knowingly responsible
for completing all work with integrity and in accordance with the policy:
(https://www.umass.edu/senate/book/academic-regulations-academic-integrity-policy).

** Accommodation statement
The University of Massachusetts Amherst is committed to providing an equal
educational opportunity for all students. If you have a documented physical,
psychological, or learning disability on file with Disability Services (DS),
you may be eligible for reasonable academic accommodations to help you succeed
in this course. If you have a documented disability that requires an
accommodation, please notify me within the first two weeks of the semester so
that we may make appropriate arrangements. For further information, please
visit Disability Services (https://www.umass.edu/disability/).

** Title IX statement
In accordance with Title IX of the Education Amendments of 1972 that prohibits
gender-based discrimination in educational settings that receive federal funds,
the University of Massachusetts Amherst is committed to providing a safe
learning environment for all students, free from all forms of discrimination,
including sexual assault, sexual harassment, domestic violence, dating
violence, stalking, and retaliation. This includes interactions in person or
online through digital platforms and social media. Title IX also protects
against discrimination on the basis of pregnancy, childbirth, false pregnancy,
miscarriage, abortion, or related conditions, including recovery. There are
resources on campus to support you. A summary of the available Title IX
resources (confidential and non-confidential) can be found at the following
link: https://www.umass.edu/titleix/resources. You do not need to make a formal
report to access them. If you need immediate support, you are not alone. Free
and confidential support is available 24 hours a day / 7 days a week / 365 days
a year at the SASA Hotline 413-545-0800.


